# Generated by Django 3.2 on 2021-04-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VMDName', models.CharField(max_length=200)),
                ('VMDLocation', models.CharField(max_length=200)),
                ('VMDLatitude', models.CharField(max_length=200)),
                ('VMDLongitude', models.CharField(max_length=200)),
                ('VMDIPAddress', models.GenericIPAddressField()),
                ('VMDPort', models.IntegerField()),
                ('VMDResolutionHeight', models.IntegerField()),
                ('VMDResolutionwidth', models.IntegerField()),
                ('VMDStatus', models.CharField(max_length=200)),
                ('VMDBrightness', models.IntegerField()),
                ('AssigneUser', models.CharField(max_length=200)),
            ],
        ),
    ]
