# Generated by Django 3.2 on 2021-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vmds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmds',
            name='VMDIPAddress',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.CreateModel(
            name='VMDGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=300)),
                ('CreatedBy', models.CharField(max_length=300)),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
                ('VMDS', models.ManyToManyField(to='app.VMDS')),
            ],
        ),
    ]
