# Generated by Django 3.2 on 2021-05-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmds',
            name='VMDPort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
