# Generated by Django 3.2 on 2021-04-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210424_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMDConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ON_OFF_Scheduling', models.BooleanField()),
                ('VMD_Brightness', models.BooleanField()),
                ('Resolution', models.BooleanField()),
                ('wakeUptime', models.TimeField(blank=True, null=True)),
                ('Sleeptime', models.TimeField(blank=True, null=True)),
                ('Reboottime', models.TimeField(blank=True, null=True)),
                ('Brightness', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('VMDS', models.ManyToManyField(to='app.VMDS')),
            ],
        ),
    ]
