# Generated by Django 3.2 on 2021-05-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vmds_vmdport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmds',
            name='VMDStatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
