# Generated by Django 3.2 on 2021-04-24 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vmdconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionDimensionAndCoOrdinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XCoOrdinates', models.IntegerField()),
                ('YCoOrdinates', models.IntegerField()),
                ('Width', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('BorderLine', models.CharField(max_length=200)),
                ('BackGroundColor', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('Duration', models.CharField(max_length=100)),
                ('RepeatCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleLineTextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('RegionDimensionAndCoOrdinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.regiondimensionandcoordinates')),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
