# Generated by Django 3.2 on 2021-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210513_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishmanagement',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='publishmanagement',
            name='RepeatCount',
        ),
        migrations.AddField(
            model_name='publishmanagement',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishmanagement',
            name='EndTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
