# Generated by Django 3.2 on 2021-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210513_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='BackGroundColor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='BorderLine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='Height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='Width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='XCoOrdinates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='YCoOrdinates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
