# Generated by Django 3.2 on 2021-05-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210513_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='combineMessae',
            field=models.TextField(blank=True, null=True),
        ),
    ]
