# Generated by Django 3.2 on 2021-04-25 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_schedule_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schedule')),
                ('message', models.ManyToManyField(to='app.TextMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vmds')),
            ],
        ),
    ]
