# Generated by Django 3.2 on 2021-04-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_publishmanagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishmanagement',
            name='vmdGroups',
            field=models.ManyToManyField(to='app.VMDGroups'),
        ),
        migrations.RemoveField(
            model_name='publishmanagement',
            name='message',
        ),
        migrations.AddField(
            model_name='publishmanagement',
            name='message',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='publishmanagement',
            name='vmd',
        ),
        migrations.AddField(
            model_name='publishmanagement',
            name='vmd',
            field=models.ManyToManyField(to='app.VMDS'),
        ),
    ]
