# Generated by Django 3.2 on 2021-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210427_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishmanagement',
            name='vmd',
            field=models.ManyToManyField(blank=True, null=True, to='app.VMDS'),
        ),
        migrations.AlterField(
            model_name='publishmanagement',
            name='vmdGroups',
            field=models.ManyToManyField(blank=True, null=True, to='app.VMDGroups'),
        ),
    ]
